name: Process YouTube Subtitles Weekly

on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m spacy download zh_core_web_sm
          python -m spacy download ja_core_news_sm
          python -m spacy download es_core_news_sm
          sudo apt-get install -y ffmpeg

      - name: Install Korean NLP dependencies
        run: |
          sudo apt-get install -y default-jre  # required for KoNLPy

      - name: Run batch processor
        run: |
          python scripts/run_batch.py

      - name: Commit processed data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/processed || true
          git commit -m "Weekly video processing update" || echo "No changes"
          git push
